version: '2'
services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/usr/app/
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/bookshelf
      PORT: 8080
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: bookshelf
